export const FORM_ASPIRANTE_BASICOS = {
  titulo: '',
  tipo_formulario: 'mini',
  alertas: true,
  modelo: 'InfoPersona',
  campos: [
    {
      etiqueta: 'input',
      claseGrid: 'form-col1',
      nombre: 'PrimerNombre',
      label_i18n: 'primer_nombre',
      placeholder_i18n: 'primer_nombre',
      requerido: true,
      tipo: 'text',
      deshabilitar: true,
    },
    {
      etiqueta: 'input',
      claseGrid: 'form-col1',
      nombre: 'SegundoNombre',
      label_i18n: 'segundo_nombre',
      placeholder_i18n: 'segundo_nombre',
      requerido: false,
      tipo: 'text',
      deshabilitar: true,
    },
    {
      etiqueta: 'input',
      claseGrid: 'form-col1',
      nombre: 'PrimerApellido',
      label_i18n: 'primer_apellido',
      placeholder_i18n: 'primer_apellido',
      requerido: true,
      tipo: 'text',
      deshabilitar: true,
    },
    {
      etiqueta: 'input',
      claseGrid: 'form-col1',
      nombre: 'SegundoApellido',
      label_i18n: 'segundo_apellido',
      placeholder_i18n: 'segundo_apellido',
      requerido: false,
      tipo: 'text',
      deshabilitar: true,
    },
    {
      etiqueta: 'mat-date',
      claseGrid: 'form-col1',
      nombre: 'FechaNacimiento',
      label_i18n: 'fecha_nacimiento',
      placeholder_i18n: 'fecha_nacimiento',
      requerido: true,
      tipo: 'date',
      deshabilitar: true,
    },
  ],
};

export const FORM_ASPIRANTE_IDENTIFICACION = {
  titulo: '',
  tipo_formulario: 'mini',
  alertas: true,
  modelo: 'InfoPersona',
  campos: [
    {
      etiqueta: 'select',
      claseGrid: 'form-col1',
      nombre: 'TipoIdentificacion',
      label_i18n: 'tipo_documento',
      placeholder_i18n: 'tipo_documento',
      requerido: true,
      tipo: 'TipoIdentificacion',
      key: 'Nombre',
      opciones: [],
      deshabilitar: true,
    },
    {
      etiqueta: 'input',
      claseGrid: 'form-col1',
      nombre: 'NumeroIdentificacion',
      label_i18n: 'numero_documento',
      placeholder_i18n: 'numero_documento',
      requerido: true,
      tipo: 'text',
      deshabilitar: true,
    },
    {
      etiqueta: 'mat-date',
      claseGrid: 'form-col1',
      nombre: 'FechaExpedicion',
      label_i18n: 'fecha_expedicion',
      placeholder_i18n: 'fecha_expedicion',
      requerido: true,
      tipo: 'date',
      deshabilitar: true,
    },
  ],
};

export const FORM_ASPIRANTE_ADICIONALES = {
  titulo: '',
  tipo_formulario: 'mini',
  alertas: true,
  modelo: 'InfoPersona',
  campos: [
    {
      etiqueta: 'input',
      claseGrid: 'form-col1',
      nombre: 'Telefono',
      label_i18n: 'telefono',
      placeholder_i18n: 'telefono',
      requerido: true,
      tipo: 'number',
      minimo: 1000,
      deshabilitar: true,
    },
    // {
    //   etiqueta: 'input',
    //   claseGrid: 'form-col1',
    //   nombre: 'Genero',
    //   label_i18n: 'genero',
    //   placeholder_i18n: 'genero',
    //   requerido: true,
    //   tipo: 'text',
    //   deshabilitar: true,
    // },
  ],
};
