export const ACTUALIZAR_NOMBRE = {
  titulo: 'solicitud_encabezado',
  tipo_formulario: 'mini',
  modelo: '',
  btn: 'Enviar',
  campos: [
    {
      etiqueta: 'input',
      tipo: 'text',
      nombre: 'FechaSolicitud',
      claseGrid: 'form-col2',
      label_i18n: 'fecha',
      deshabilitar: true,
      requerido: true,
    },
    {
      etiqueta: 'input',
      tipo: 'text',
      label_i18n: 'nombre_actual',
      nombre: 'NombreActual',
      claseGrid: '',
      deshabilitar: true,
      requerido: true,
    },
    {
      etiqueta: 'input',
      tipo: 'text',
      nombre: 'ApellidoActual',
      deshabilitar: true,
      claseGrid: '',
      label_i18n: 'apellido_actual',
      requerido: true,
    },
    {
      etiqueta: 'input',
      tipo: 'text',
      nombre: 'NombreNuevo',
      claseGrid: '',
      label_i18n: 'nombre_nuevo',
      requerido: true,
    },
    {
      etiqueta: 'input',
      tipo: 'text',
      nombre: 'ApellidoNuevo',
      claseGrid: '',
      label_i18n: 'apellido_nuevo',
      requerido: true,
    },
    {
      etiqueta: 'file',
      claseGrid: '',
      clase: 'form-control',
      nombre: 'Documento',
      label_i18n: 'soporte_id',
      placeholder_i18n: 'soporte_documento',
      requerido: true,
      tipo: 'pdf',
      tipoDocumento: 25,
      formatos: 'pdf',
      url: '',
      tamanoMaximo: 2,
    },
    {
      etiqueta: 'button',
      claseGrid: '',
      nombre: 'ButonEditar',
      id: 'noMostrar',
      tipo: 'mat-button',
      label_i18n: 'responder_solicitud',
      label_i18n_estudiante: 'modificar_solicitud',
    },
  ],
}
